# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.3.9-apache-node-browsers
      - image: circleci/mysql:5.7.28
        environment:
          MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
          MYSQL_DATABASE: $MYSQL_DATABASE
          MYSQL_USER: $MYSQL_USER
          MYSQL_PASSWORD: $MYSQL_PASSWORD
          

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      # - image: circleci/mysql:5.7-ram
      #
      # - image: redis:2.8.19

    steps:
      - checkout

      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev 
      - run: sudo docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
      - run: sudo docker-php-ext-install zip
      - run: sudo docker-php-ext-install exif
      - run: sudo docker-php-ext-install pdo_mysql
      - run: sudo docker-php-ext-install mbstring
      - run: sudo docker-php-ext-install gd
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI
          command: |
            sudo apt-get install default-mysql-client

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run: sudo chmod +x bin/cake
      - run: sudo chmod 777 config/database.php
      - run: sudo chmod 777 config/production_key.php
      - run: sudo chmod -R 777 logs
      - run: sudo chmod -R 777 tmp
      - run: sudo mkdir webroot/exports
      - run: sudo chmod 777 webroot/exports

      - run: sudo chmod 777 webroot/uploads

      - run: sudo mkdir webroot/uploads/images
      - run: sudo chmod 777 webroot/uploads/images

      - run: sudo mkdir webroot/uploads/images/thumbnails
      - run: sudo chmod 777 webroot/uploads/images/thumbnails

      - run: sudo mkdir webroot/uploads/images/thumbnails/300x300
      - run: sudo chmod 777 webroot/uploads/images/thumbnails/300x300

      - run: sudo mkdir webroot/uploads/images/thumbnails/480x270
      - run: sudo chmod 777 webroot/uploads/images/thumbnails/480x270

      - run: sudo mkdir webroot/uploads/documents
      - run: sudo chmod 777 webroot/uploads/documents

      - run: sudo mkdir webroot/uploads/videos
      - run: sudo chmod 777 webroot/uploads/videos

      - run: sudo mkdir webroot/uploads/custom-pages
      - run: sudo chmod 777 webroot/uploads/custom-pages

      - run: sudo chmod 777 webroot/uploads/themes
      
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

      - run: sudo chmod +x bin/cake
      - run: sudo chmod 777 config/database.php
      - run: sudo chmod 777 config/production_key.php
      - run: sudo chmod -R 777 logs
      - run: sudo chmod -R 777 tmp
      - run: sudo mkdir webroot/exports
      - run: sudo chmod 777 webroot/exports

      - run: sudo chmod 777 webroot/uploads

      - run: sudo mkdir webroot/uploads/images
      - run: sudo chmod 777 webroot/uploads/images

      - run: sudo mkdir webroot/uploads/images/thumbnails
      - run: sudo chmod 777 webroot/uploads/images/thumbnails

      - run: sudo mkdir webroot/uploads/images/thumbnails/300x300
      - run: sudo chmod 777 webroot/uploads/images/thumbnails/300x300

      - run: sudo mkdir webroot/uploads/images/thumbnails/480x270
      - run: sudo chmod 777 webroot/uploads/images/thumbnails/480x270

      - run: sudo mkdir webroot/uploads/documents
      - run: sudo chmod 777 webroot/uploads/documents

      - run: sudo mkdir webroot/uploads/videos
      - run: sudo chmod 777 webroot/uploads/videos

      - run: sudo mkdir webroot/uploads/custom-pages
      - run: sudo chmod 777 webroot/uploads/custom-pages
      
      - run: sudo chmod 777 webroot/uploads/themes
      
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master